CREATE TABLE employee(
    EMPLOYEE_ID INT AUTO INCREMENT NOT NULL,
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    EMAIL VARCHAR(30),
    PHONE_NUMBER VARCHAR(10),
    HIRE_DATE DATE,
    JOB_ID ENUM('AD_PRES','AD_VP','IT_PROG'),
    SALARY DECIMAL(10,2),
    COMMISSION_PTC(2.2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT,
    CONSTRAINT PRIMARY KEY(FIRST_NAME) 
)

UPDATE employee SET EMAIL='not available';

UPDATE employee SET EMAIL='not available' AND COMMISSION_PTC=0.10;

UPDATE employee SET EMAIL='not available' AND COMMISSION_PTC=0.10 WHERE DEPARTMENT_ID=110;

UPDATE employee SET EMAIL='not available' WHERE COMMISSION_PTC<0.2 AND DEPARTMENT_ID=80;

UPDATE employee SET SALARY= 8000.00 WHERE EMPLOYEE_ID =105 AND SALARY < 5000;

UPDATE employee SET JOB_ID = 'SH_CLERK' WHERE EMPLOYEE_ID =118 AND DEPARTMENT_ID = 30;